name: Alembic Migration Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'migrations/**'
      - 'alembic.ini'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-migrations:
    name: Test Alembic Migrations
    runs-on: ubuntu-latest
    # These permissions are needed for PR comments
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-alembic

      - name: Test Alembic Migrations
        uses: OpenMindUA/alembic-actions/test@v0.2
        with:
          # Relative path to the alembic.ini file
          alembic_ini_path: 'alembic.ini'
          
          # Test options (all enabled by default)
          test_single_head: 'true'
          test_upgrades: 'true'
          test_downgrades: 'true'
          test_model_definitions: 'true'
          
          # Database options (defaults to SQLite in-memory)
          db_url: 'sqlite:///./test_migrations.db'
          
          # Additional optional configurations
          # target_branch: 'main'  # Base branch to compare against (default: main or master)
          # migration_script_path: 'migrations' # Path to the migrations directory (default: derived from alembic.ini)