name: Alembic Migration Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'app/**'
      - 'migrations/**'
      - 'alembic.ini'

jobs:
  check-migrations:
    name: Validate Alembic Migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install alembic-review
        run: |
          pip install git+https://github.com/OpenMindUA/alembic-actions.git@v1

      - name: Check Alembic Migrations
        run: |
          # Determine the base branch (main or master)
          BASE_BRANCH="main"
          if ! git ls-remote --exit-code --heads origin main; then
            BASE_BRANCH="master"
          fi

          # Run the alembic-review command
          PYTHONPATH=$PYTHONPATH:$(pwd) alembic-review \
            --alembic-ini-path alembic.ini \
            --target-branch $BASE_BRANCH \
            --check-revision-files \
            --check-revision-order \
            --check-downgrade \
            --check-upgrade \
            --check-duplicate-ops